### ISSUE TITLE
How to run the project locally

### ISSUE THREAD

**Issue by shubhamraj-samsung** [dev-details/ai-code-example#1]
Hi @six8 
I am also following the coding challenges and wanted to use your solution as a reference to learn python
I am new to python and am having difficulty in running your projects on my system

Basically I am facing error like this 
`ModuleNotFoundError: No module named 'pytest'` 

Do I need to pip install every dependency manually?
There is one `pyproject.toml` file where the dependencies seems to be specified
I tried running `pip install pyproject.toml` but on running `tests.py` I am still facing the same error

Can you please add additional documentation as how to run your projects locally
TIA

**Comment by six8** [comment]
Done. I've updated the `README.md`. I had to update a few packages to the latest versions. The results you get from the article may differ a little bit from the current state of the repo.
